name: Solution Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore
      run: dotnet restore ./Sources/ByteZoo.Blog.sln
    - name: Build
      run: dotnet build ./Sources/ByteZoo.Blog.sln --no-restore --configuration Release
    - name: Test
      run: dotnet test ./Sources/ByteZoo.Blog.sln --no-build --verbosity normal
